-- Author AUTHOR

SET SERVEROUTPUT ON
SET ECHO ON 
SET AUTO OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SPOOL RB_00_CONTROL_SCRIPT.log

SET DEFINE OFF


@@ Rollback/RB_01_ABCD.sql

COMMIT;
SPOOL OFF;