--liquibase formatted sql

--changeset ad185291:abcd-457-1
INSERT INTO FIELD (FLD_NAME,FLD_INT_ID,FLD_INT_SEQ,FLD_BITMAPPED_FLD_FLAG,FLD_GRP_FLAG,FLD_GRP_SEQ,FLD_INTERNAL_DAT_ID,FLD_PARENT,FLD_DATA_MIN_LENGTH,FLD_DATA_MAX_LENGTH,FLD_INTERNAL_NAME,FLD_REPEAT_FLAG,FLD_LAST_UPDATE_TS,FLD_MTI_FLAG) VALUES ('abcd Remote ATM Indicator', 107, (SELECT MAX(FLD_INT_SEQ) + 1 FROM FIELD WHERE FLD_INT_ID = 107), 'N','N',0,28,'N',0,0,'abcd_REMOTE_IND', 'N', CURRENT_TIMESTAMP, 'N');
--rollback DELETE FROM FIELD  WHERE FLD_NAME = 'abcd Remote ATM Indicator';

--changeset ad185291:abcd-457-2
INSERT INTO SEGMENT_FIELD (SGF_SEG_ID,SGF_FLD_ID,SGF_SEQ,SGF_MTI_INDICATOR,SGF_LAST_UPDATE_TS,SGF_MANDATORY_FLAG) VALUES ((SELECT SEG_ID FROM SEGMENT WHERE SEG_INT_ID =  107 AND SEG_NAME = 'Generic Body'),(SELECT FLD_ID FROM FIELD WHERE FLD_NAME = 'abcd Remote ATM Indicator'),(SELECT MAX(SGF_SEQ) + 1 FROM SEGMENT_FIELD WHERE SGF_SEG_ID = (SELECT SEG_ID FROM SEGMENT WHERE SEG_INT_ID =  107 AND SEG_NAME = 'Generic Body')),'N', CURRENT_TIMESTAMP, 'N');
--rollback DELETE FROM SEGMENT_FIELD WHERE SGF_SEG_ID = (SELECT SEG_ID FROM SEGMENT WHERE SEG_INT_ID =  107 AND SEG_NAME = 'Generic Body') AND SGF_FLD_ID = (SELECT FLD_ID FROM FIELD WHERE FLD_NAME = 'abcd Remote ATM Indicator');

--changeset ad185291:abcd-457-3
INSERT INTO FIELD (FLD_NAME,FLD_INT_ID,FLD_INT_SEQ,FLD_BITMAPPED_FLD_FLAG,FLD_GRP_FLAG,FLD_GRP_SEQ,FLD_INTERNAL_DAT_ID,FLD_PARENT,FLD_DATA_MIN_LENGTH,FLD_DATA_MAX_LENGTH,FLD_INTERNAL_NAME,FLD_REPEAT_FLAG,FLD_LAST_UPDATE_TS,FLD_MTI_FLAG) VALUES ('abcd Social Deprivation Indicator', 107, (SELECT MAX(FLD_INT_SEQ) + 1 FROM FIELD WHERE FLD_INT_ID = 107), 'N','N',0,28,'N',0,0,'abcd_SOCIAL_DEP_IND', 'N', CURRENT_TIMESTAMP, 'N');
--rollback DELETE FROM FIELD  WHERE FLD_NAME = 'abcd Social Deprivation Indicator';

--changeset ad185291:abcd-457-4
INSERT INTO SEGMENT_FIELD (SGF_SEG_ID,SGF_FLD_ID,SGF_SEQ,SGF_MTI_INDICATOR,SGF_LAST_UPDATE_TS,SGF_MANDATORY_FLAG) VALUES ((SELECT SEG_ID FROM SEGMENT WHERE SEG_INT_ID =  107 AND SEG_NAME = 'Generic Body'),(SELECT FLD_ID FROM FIELD WHERE FLD_NAME = 'abcd Social Deprivation Indicator'),(SELECT MAX(SGF_SEQ) + 1 FROM SEGMENT_FIELD WHERE SGF_SEG_ID = (SELECT SEG_ID FROM SEGMENT WHERE SEG_INT_ID =  107 AND SEG_NAME = 'Generic Body')),'N', CURRENT_TIMESTAMP, 'N');
--rollback DELETE FROM SEGMENT_FIELD WHERE SGF_SEG_ID = (SELECT SEG_ID FROM SEGMENT WHERE SEG_INT_ID =  107 AND SEG_NAME = 'Generic Body') AND SGF_FLD_ID = (SELECT FLD_ID FROM FIELD WHERE FLD_NAME = 'abcd Social Deprivation Indicator');

--changeset ks185279:abcd-164-1
INSERT INTO FIELD (FLD_NAME,FLD_INT_ID,FLD_INT_SEQ,FLD_BITMAPPED_FLD_FLAG,FLD_GRP_FLAG,FLD_GRP_SEQ,FLD_INTERNAL_DAT_ID,FLD_PARENT,FLD_DATA_MIN_LENGTH,FLD_DATA_MAX_LENGTH,FLD_INTERNAL_NAME,FLD_REPEAT_FLAG,FLD_LAST_UPDATE_TS,FLD_MTI_FLAG) VALUES ('abcd Get All Balances', 107, (SELECT MAX(FLD_INT_SEQ) + 1 FROM FIELD WHERE FLD_INT_ID = 107), 'N','N',0,28,'N',0,0,'GetAllBalance', 'N', CURRENT_TIMESTAMP, 'N');
--rollback DELETE FROM FIELD  WHERE FLD_NAME = 'abcd Get All Balances';

--changeset ks185279:abcd-164-2
INSERT INTO SEGMENT_FIELD (SGF_SEG_ID,SGF_FLD_ID,SGF_SEQ,SGF_MTI_INDICATOR,SGF_LAST_UPDATE_TS,SGF_MANDATORY_FLAG) VALUES ((SELECT SEG_ID FROM SEGMENT WHERE SEG_INT_ID =  107 AND SEG_NAME = 'Generic Body'),(SELECT FLD_ID FROM FIELD WHERE FLD_NAME = 'abcd Get All Balances'),(SELECT MAX(SGF_SEQ) + 1 FROM SEGMENT_FIELD WHERE SGF_SEG_ID = (SELECT SEG_ID FROM SEGMENT WHERE SEG_INT_ID =  107 AND SEG_NAME = 'Generic Body')),'N', CURRENT_TIMESTAMP, 'N');
--rollback DELETE FROM SEGMENT_FIELD WHERE SGF_SEG_ID = (SELECT SEG_ID FROM SEGMENT WHERE SEG_INT_ID =  107 AND SEG_NAME = 'Generic Body') AND SGF_FLD_ID = (SELECT FLD_ID FROM FIELD WHERE FLD_NAME = 'abcd Get All Balances');
