--liquibase formatted sql

--changeset rl185192:abcd-468-3
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(1) FROM HSM_KEY_SET WHERE HKS_NAME='VISA_DPS_KEYSET'
INSERT INTO HSM_KEY_SET(HKS_NAME, HKS_LAST_UPDATE_TS) VALUES ('VISA_DPS_KEYSET', CURRENT_TIMESTAMP);
--rollback DELETE FROM HSM_KEY_SET WHERE HKS_NAME='VISA_DPS_KEYSET';

--changeset rl185192:abcd-468-4
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(1) FROM HSM_KEY_GROUP WHERE HKG_NAME='PAS_CREDIT_NETWORK_KEY_GROUP'
INSERT INTO HSM_KEY_GROUP(HKG_NAME, HKG_HKT_NAME, HKG_DESCRIPTION, HKG_COUNT, HKG_HLK_ID, HKG_LAST_UPDATE) VALUES ('PAS_CREDIT_NETWORK_KEY_GROUP', 'ZPK', 'PAS_CREDIT_NETWORK_KEY_GROUP', '1', '1', CURRENT_TIMESTAMP);
--rollback DELETE FROM HSM_KEY_GROUP WHERE HKG_NAME='PAS_CREDIT_NETWORK_KEY_GROUP';

--changeset rl185192:abcd-468-5
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(1) FROM HSM_KEY_GROUP WHERE HKG_NAME='PAS_DEBIT_NETWORK_KEY_GROUP'
INSERT INTO HSM_KEY_GROUP(HKG_NAME, HKG_HKT_NAME, HKG_DESCRIPTION, HKG_COUNT, HKG_HLK_ID, HKG_LAST_UPDATE) VALUES ('PAS_DEBIT_NETWORK_KEY_GROUP', 'ZPK', 'PAS_DEBIT_NETWORK_KEY_GROUP', '1', '1', CURRENT_TIMESTAMP);
--rollback DELETE FROM HSM_KEY_GROUP WHERE HKG_NAME='PAS_DEBIT_NETWORK_KEY_GROUP';

--changeset rl185192:abcd-468-6
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(1) FROM NETWORK_CONNECTION WHERE NTC_NAME = 'VISA_DPS' AND NTC_HKS_NAME = 'VISA_DPS_KEYSET';
UPDATE NETWORK_CONNECTION SET NTC_HKS_NAME = 'VISA_DPS_KEYSET', NTC_LAST_UPDATE_TS = CURRENT_TIMESTAMP WHERE NTC_NAME = 'VISA_DPS';
--rollback UPDATE NETWORK_CONNECTION SET NTC_HKS_NAME = NULL, NTC_LAST_UPDATE_TS = CURRENT_TIMESTAMP WHERE NTC_NAME = 'VISA_DPS';

